types:
    Action:
        properties:
            actionStatus:
            agent:
            participant:
            object:
            result:
            instrument:
            startTime:
            endTime:
            location:
            error:

