#Entities for schema generator - see: https://api-platform.com/docs/schema-generator/configuration/

#Syncronize with config/api_platform/resources.yaml

types:
    Action:
        properties:
            actionStatus:
            agent:
            participant:
            object:
            result:
            instrument:
            startTime:
            endTime:
            location:
            error:

    ActionStatusType: # Enumeration
        properties: {} # Remove all properties of the parent class

annotationGenerators:
    - ApiPlatform\SchemaGenerator\AnnotationGenerator\PhpDocAnnotationGenerator
    - ApiPlatform\SchemaGenerator\AnnotationGenerator\DoctrineOrmAnnotationGenerator
    - ApiPlatform\SchemaGenerator\AnnotationGenerator\ConstraintAnnotationGenerator
    - ApiPlatform\SchemaGenerator\AnnotationGenerator\SerializerGroupsAnnotationGenerator
