#Entities for schema generator - see: https://api-platform.com/docs/schema-generator/configuration/

#Syncronize with config/api_platform/resources.yaml

types:
    Action:
        properties:
            actionStatus:
            agent:
                range: Thing # Person or Organization
            participant:
                range: Thing # Person or Organization
            object:
            result:
            instrument:
            startTime:
            endTime:
            location:
            error:

    ActionStatusType: # Enumeration
        properties: {} # Remove all properties of the parent class

    Organization:
        properties:
            name:

    Person:
        properties:
            name:

    Thing:
        doctrine:
            inheritanceMapping: "@ORM\\Entity\n * @ORM\\InheritanceType(\"JOINED\")"
        properties: {}

annotationGenerators:
    - ApiPlatform\SchemaGenerator\AnnotationGenerator\PhpDocAnnotationGenerator
    - ApiPlatform\SchemaGenerator\AnnotationGenerator\DoctrineOrmAnnotationGenerator
    # - ApiPlatform\SchemaGenerator\AnnotationGenerator\ApiPlatformCoreAnnotationGenerator
    - ApiPlatform\SchemaGenerator\AnnotationGenerator\ConstraintAnnotationGenerator
    - ApiPlatform\SchemaGenerator\AnnotationGenerator\SerializerGroupsAnnotationGenerator
